name: chat_web_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  url_strategy:
  cupertino_icons: ^1.0.2
  hive_flutter:
  open_filex:
  firebase_storage:
  cloud_firestore:
  firebase_auth:
  flutter_chat_types: ^3.6.1
  flutter_firebase_chat_core:
  firebase_messaging:
  flutter_link_previewer:
  flutter_parsed_text:
  url_launcher:
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  get:
  intl:
  file_picker:
  image_picker:
  mime:
  diffutil_dart: ^3.0.0
  get_it: any
  http: any
  logger: ^1.1.0
  linkify: ^5.0.0
  photo_view: ^0.14.0
  scroll_to_index: ^3.0.1
  shared_preferences:
  firebase_core:
  firebase_analytics:
  visibility_detector: ^0.4.0+2
  go_router: ^6.5.8
  drawable_text:
    git:
      url: https://github.com/saedAlHanash/drawable_text
      ref: html

  image_multi_type:
    git:
      url: https://github.com/saedAlHanash/image_multi_type


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true
  assets:
    - assets/svg/
    - assets/images/



